apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticService.transport.name }}
  labels:
    {{- include "es-cluster.labels" . | nindent 4 }}
spec:
  ports:
  - name: transport
    port: {{ .Values.elasticService.transport.port }}
    targetPort: transport
  selector:
    {{- include "es-cluster.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticService.http.name }}
  labels:
    {{- include "es-cluster.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .Values.elasticService.http.port }}
    targetPort: http
  selector:
    {{- include "es-cluster.selectorLabels" . | nindent 4 }}