apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.elastic.statefulSetName }}
  labels:
    {{- include "es-cluster.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "es-cluster.selectorLabels" . | nindent 6 }}
  serviceName: {{ .Values.elastic.service.transport.name }}
  updateStrategy:
    type: RollingUpdate
  replicas: {{ .Values.elastic.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "es-cluster.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        {{- if .Values.elastic.useAntiAffinity }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.elastic.statefulSetName }}
            topologyKey: "kubernetes.io/hostname"
        {{- end }}
      initContainers:
      - name: chown
        image: alpine
        volumeMounts:
        - name: {{ .Values.elastic.volume.data.name }}
          mountPath: /data
        command: ["chown", "1000:root", "/data"]
      - name: init-sysctl
        image: alpine
        securityContext:
          privileged: true
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
      containers:
      - name: {{ .Values.elastic.statefulSetName }}
        image: "{{ .Values.elastic.image }}:{{ .Chart.AppVersion }}"
        resources:
{{ toYaml .Values.elastic.resources | indent 10 }}
        env:
        - name: ES_JAVA_OPTS
          value: {{ .Values.elastic.env.javaOpts }}
        - name: cluster.name
          value: {{ .Values.elastic.clusterName }}
        - name: discovery.seed_hosts
          value: {{ include "nodesFQDN" . }}
        - name: cluster.initial_master_nodes
          value: {{ include "masterNodes" .Values}}
        - name: xpack.security.transport.ssl.enabled
          value: "{{ .Values.elastic.xpack.transportSSLEnabled }}"
        {{- if .Values.elastic.xpack.transportSSLEnabled }}
        - name: xpack.monitoring.collection.enabled
          value: "{{ .Values.elastic.xpack.monitoringCollectionEnabled }}"
        - name: xpack.security.transport.ssl.verification_mode
          value: {{ .Values.elastic.xpack.transportSSLMode }}
        - name: xpack.security.transport.ssl.key
          value: {{ .Values.elastic.volume.certificates.mount }}/tls.key
        - name: xpack.security.transport.ssl.certificate
          value: {{ .Values.elastic.volume.certificates.mount }}/tls.crt
        - name: xpack.security.transport.ssl.certificate_authorities
          value: {{ .Values.elastic.volume.certificates.mount }}/ca.crt
        {{- end }}
        volumeMounts:
        - name: {{ .Values.elastic.volume.data.name }}
          mountPath: /usr/share/elasticsearch/data
        {{- if .Values.elastic.xpack.transportSSLEnabled }}
        - name: {{ .Values.elastic.volume.certificates.name }}
          mountPath: {{ .Values.elastic.volume.certificates.mount }}
        {{- end}}
        ports:
        - name: http
          containerPort: 9200
        - name: transport
          containerPort: 9300
        livenessProbe:
          httpGet:
            path: /_cat/health
            port: 9200
          initialDelaySeconds: 50
          periodSeconds: 10
      volumes:
      {{- if .Values.elastic.xpack.transportSSLEnabled }}
      - name: {{ .Values.elastic.volume.certificates.name}}
        secret:
          secretName: {{ .Values.elastic.transportCertificate.secret }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.elastic.volume.data.name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.elastic.volume.data.size }}