# Default values for es-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Override the name of the chart in labels
nameOverride: ""

certManager:
  # -- Selfsigned certificate ClusterIssuer Name
  clusterIssuerName: selfsigned-issuer

elasticCA:
  # -- Resource name for internal CA signing certificate
  certificateName: elastic-ca
  # -- Secret name to store the internal CA signing certificate
  certificateSecret: elastic-ca-certificate
  # -- CA Common Name
  certificateCommonName: "Internal Certificate CA"
  # -- Certificate issuer name
  issuerName: elastic-ca-issuer

elastic:
  # -- Elastisearch cluster name. This is Elastic specific, not Kubernetes resource
  clusterName: es-k8s-cluster
  # -- Elasticsearch cluster StetefulSet name. This will be used as base for node names
  statefulSetName: "es-node"
  # -- Number of Elastic nodes to be deployed
  replicaCount: 3
  # -- Image repository
  image: docker.elastic.co/elasticsearch/elasticsearch
  # -- If enabled, will not allow two pods to run on the same node
  useAntiAffinity: true
  transportCertificate:
    # -- Transport certificate object name
    name: elastic-transport
    # -- Secret name to store transport certificate
    secret: elastic-transport-certificate
  service:
    transport:
      # -- Transport service name
      name: "es-transport"
      # -- Transport service port
      port: 9300
    http:
      # -- HTTP service name
      name: "es-public"
      # -- HTTP service port
      port: 80
  volume:
    certificates:
      # -- Volume name for transport certificate
      name: elastic-transport-certificate
      # -- Volume mountpoint for transport certificate
      mount: /usr/share/elasticsearch/config/certs
    # -- Data volume name and size
    data:
        name: data
        size: 1Gi
  env:
    # -- JAVA_OPTS value to be passed as startup argument
    javaOpts: "-Xms512m -Xmx512m"
  xpack:
    # -- If enabled, Elasticsearch will require user authentication
    securityEnabled: false
    # -- If enabled, internal cluster communication will be encrypted using the transport certificate
    transportSSLEnabled: false
    # -- Transport validation mode as defined by Elastic. In "certificate" mode, certificate is matched against CA, hostnames are not validates
    transportSSLMode: certificate
    # -- If enabled, internal monitoring collection is enabled
    monitoringCollectionEnabled: true
  resources:
    # -- Resource requests
    requests:
      cpu: 250m
      memory: 1024Mi
    # -- Resource limits
    limits:
      cpu: 1000m
      memory: 2048Mi

ingress:
  # -- If enabled, creates ingress objects for deployed resources
  enabled: false
  # -- If enabled, nginx ingess controller will be deployed
  deployController: false
  # -- Ingress name
  name: elastic-ingress
  # -- Path for Elasticsearch cluster
  elasticPath: es
  # -- Path for Kibana
  kibanaPath: kibana

kibana:
  # -- If enabled, Kibana will de deployed
  enabled: false
  # -- Kibana service name
  serviceName: kibana-service
  # -- Kibana service port
  servicePort: 80
  # -- Kibana deployment name
  deploymentName: kibana
  # -- Value for app label for Kibana resources
  appLabel: kibana
  # -- Kibana image
  image: docker.elastic.co/kibana/kibana
  # -- Username for Kibana to Elastic communication
  elasticUsername: kibana_system

ingress-nginx:
  # -- Needed as a workaround for a bug in the nginx controller chart
  fullnameOverride: nginx-ingress-ingress-nginx